[workspace]
members = [
    "programs/zara-staking"
]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zara_staking = "8mdqFh7gtdZb2jpUtzoQRFwmjbGE3KAfzq3TqEJxknMt"

[programs.devnet]
zara_staking = "8mdqFh7gtdZb2jpUtzoQRFwmjbGE3KAfzq3TqEJxknMt"

[programs.mainnet]
zara_staking = "8mdqFh7gtdZb2jpUtzoQRFwmjbGE3KAfzq3TqEJxknMt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/mayurchougule/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.8"